### ISSUE TITLE
Iris Shaders fails to download

### ISSUE THREAD

**Issue by celestefox** [copygirl/humanity-modpack#2]
`java.io.IOException: Server returned HTTP response code: 403 for URL: https://cdn.modrinth.com/data/YL57xq9U/versions/mc1.18-1.1.3/iris-mc1.18-1.1.3.jar`

Not really sure what's going on there since i can dl it in browser, at least after navigating through the site?

**Comment by copygirl** [comment]
I suppose they renamed the file (from `1.18` to `1.18.1`) in the existing release and that's breaking the mod download. I will try to put some effort into updating the pack soon.

**Comment by copygirl** [comment]
Updated the pack so this is fixed.
